### ISSUE TITLE
Program keeps crashing R!

### ISSUE THREAD

**Issue by AbbyKimball** [nolanlab/citrus#110] opened 2017-02-27 23:11 UTC
Hello! I've tried this a couple of times and R keeps unexpectedly closing. Is this a common problem?

**Comment by AbbyKimball** [comment] 2017-02-27 23:29
Here is the code I have, I followed the directions on the wiki:

install.packages("glmnet") 
install.packages("pamr")
install.packages("ggplot2")
install.packages("ggplot2")
install.packages("Rclusterpp")
source("http://bioconductor.org/biocLite.R")
biocLite("flowCore")
biocLite("impute")
install.packages("samr")
install.packages("shiny")
install.packages("brew")
install.packages("devtools")
library("devtools")
install_github('nolanlab/citrus')
library("citrus")
citrus.launchUI()
g++-mp-4.8 -v
nano ~/.R/Makevars
install.packages("Matrix")
install.packages(c("Rcpp","RcppEigen","Rclusterpp"),type="source")
library("devtools")
install_github('nolanlab/citrus')
library("citrus")
citrus.launchUI()
library("citrus")
citrus.launchUI()

You see it begins, but seems to get stuck on the clustering part: 

<img width="1436" alt="screen shot 2017-02-27 at 4 19 54 pm" src="https://cloud.githubusercontent.com/assets/24797260/23384560/c6608650-fd08-11e6-8346-d97cdd60388b.png">

And then I get:

<img width="428" alt="screen shot 2017-02-27 at 4 27 35 pm" src="https://cloud.githubusercontent.com/assets/24797260/23384860/dd942768-fd09-11e6-8d15-19045f71f92a.png">

**Comment by SamGG** [comment] 2017-02-28 07:36
Hi,
I would try to decrease the number of events before the clustering step. 40 000 events sounds better for testing.
HTH

**Comment by AbbyKimball** [comment] 2017-02-28 17:43
Thanks for the reply :)

From playing around on cytobank it seems like lowering your events results in different CITRUS results. Do you know if these differences are significant?

**Comment by AbbyKimball** [comment] 2017-02-28 17:51
I've tried it now with 5,000 events per sample and 1,000 events per sample. Still crashes.

**Comment by rbruggner** [comment] 2017-03-01 05:32
Hi - sorry you're experiencing crashing. Could you tell me what version of Mac OS X you're using?

**Comment by SamGG** [comment] 2017-03-01 08:21
Robert is definitevily the guru for Macintosh issues.
Concerning the sampling, here is my opinion. Lowering too much the number of events will lead to some kind of loss of resolution: a real effect might be unseen. I haven't done any test concerning this aspect yet. What I understand from the Citrus algorithm is the following. Let's say we are interested in comparing condition A vs B, each made of 8 or more biological samples (this is the simplest example). Citrus builds a hierarchical clustering of sampled events from FCS files of condition A and B. In the resulting tree, Citrus will then consider only nodes with more than a defined percentage of events. This user defined threshold is applied to the FCS file merging events of conditions A and B. Therefore, if a population is 2% in condition A and 0% in condition B, the percentage in the mix will be 1%. I would then recommand to set the threshold less than 1% for such a population. Let's go with 0.5%. For the nodes of the hierarchical tree that aggregated more then 0.5%, Citrus will test if the percentage of events is statistically different in condition A versus B. If the threshold was set to 2%, the population of interest will certainly be aggregated with events of a different profile, leading to an inhomogeneous cluster of events. Due to the mixing of events, the difference in percentage might be statistically not significant. This sounds like a loss of resolution.
IMHO:
- don't lower too much the final number of events of the merged file, except for testing the computational setup.
- as events from conditions A and B are merged, set the percentage of events threshold to a rational value.
- because of the merging step, Citrus (as well as SPADE and many other algorithms) considers that a population of events is at the same position in the multi-parameters space, ie inter-individuals variation of position are not adjusted and participate to the statistical dispersion.

**Comment by AbbyKimball** [comment] 2017-03-01 19:51
Robert, I looked over the issue you sent along and I added the code you provided for potential memory leak:

install.packages(c("Rcpp","RcppEigen"),type="source")
library("devtools")
install_github('nolanlab/Rclusterpp')
install_github('nolanlab/citrus')

 I am on macOS Sierra Version 10.12.1 

Sam, per your recommendation here, and on the linked issue I first lowered the Minimum Cluster Size to 1 (the program still crashed), and then to .5 and the program still crashed.

I read somewhere that having uneven samples (4 in one group and 5 in another for this case) could affect the algorithm, is this really true? 

I've attached files of the set up. 

<img width="997" alt="screen shot 2017-03-01 at 12 50 37 pm" src="https://cloud.githubusercontent.com/assets/24797260/23478201/cb0ba614-fe7d-11e6-8f44-0d7adfd61df9.png">
<img width="1414" alt="screen shot 2017-03-01 at 12 50 08 pm" src="https://cloud.githubusercontent.com/assets/24797260/23478202/cb1a475a-fe7d-11e6-87ed-e48e693ff0a9.png">
<img width="1424" alt="screen shot 2017-03-01 at 12 49 57 pm" src="https://cloud.githubusercontent.com/assets/24797260/23478203/cb1cceee-fe7d-11e6-862f-ed9d9ca8048b.png">
<img width="1416" alt="screen shot 2017-03-01 at 12 50 15 pm" src="https://cloud.githubusercontent.com/assets/24797260/23478204/cb1e5728-fe7d-11e6-94ae-379b70575433.png">
<img width="1316" alt="screen shot 2017-03-01 at 12 48 59 pm" src="https://cloud.githubusercontent.com/assets/24797260/23478205/cb209ef2-fe7d-11e6-8bd2-bbcc18edeaa2.png">

**Comment by rbruggner** [comment] 2017-03-01 20:54
Abby, does Citrus still crash after you've installed Rclusterpp from source, e:g:
```
R> library("devtools")
R> install_github('nolanlab/Rclusterpp')
```

**Comment by SamGG** [comment] 2017-03-01 20:57
Dear Abby, I really think that the problem is due to some compilation issue. Parameter setup should not lead to a crash. I think Robert could also explain you how to run the script (created by the Shiny interface) from command line.
Please do find a simple code that may help to understand the faulty code. This code should lead to the following graphics.
```r
library(Rclusterpp)
# Matrix size
nc = 20
nr = 10000
# Generate some random data
set.seed(123)
some.data = matrix(rnorm(nc*nr), ncol = nc)
# Define a population with a different mean value
some.data[1:1000, 1:(nc %/% 4)] = some.data[1:1000, 1:(nc %/% 4)] + 1
# Do clustering
hc = Rclusterpp.hclust(some.data)
hc
# Optional process: cut the hierarchical tree in 10 clusters
hc.cut.members = cutree(hc, k = 10)
hc.cut.mean = apply(some.data, 2, function(x) tapply(x, hc.cut.members, mean))
hc.cut.mean = as.matrix(hc.cut.mean)
plot(hclust(dist(hc.cut.mean)))
# Alternative display
image(some.data)
image(hc.cut.mean)
```
![rplot](https://cloud.githubusercontent.com/assets/3333348/23480932/f9974d52-fec9-11e6-913f-68bb686674e6.png)

**Closed** 2018-04-10 00:39 UTC
