### ISSUE TITLE
Error in Studio after citrus.launchUI()

### ISSUE THREAD

**Issue by LisaMarieKronstad** [nolanlab/citrus#99] opened 2016-07-25 23:48 UTC
After using citrus successfully in 2015, my lab now receives the following output after entering the citrus.launchUI() command and selecting the folder with the .fcs files. 

"Launching citrus interface with target directory: /Users/BlishLab/Desktop/LMK_CyTOF_Rawn 

Scanning parameters in FCS files
Reading parameters in M_H1_24_Ligand_160518_23_normalized.fcs
the text section does not end with delimiter: \\. The last keyword is dropped.
the text section does not end with delimiter: \\. The last keyword is dropped."

and then the following error

"Error in value[[3L]](cond) : 
  Unexpected Error: Error in pnames[sapply(pnames, nchar) < 3] = parameterNames[sapply(pnames, : NAs are not allowed in subscripted assignments"

Any help would be greatly appreciated. 
Thank you.

**Comment by rbruggner** [comment] 2016-07-26 00:00
This sounds like the parameter metadata in the FCS file is malformed and hence, Citrus cannot read it using the flowCore package. I would suggest trying to see if you can read the FCS file using flowCore directly. Something like:

`library("flowCore")
file = read.fcs("/PATH/TO/FILE.FCS")
pData(parameters(file))`

If that fails, then you will need to fix the FCS file before flowCore (and Citrus) will be able to read it.

**Comment by LisaMarieKronstad** [comment] 2016-07-26 16:59
Hi Rob,

Thank you for your response,
------------------
Lisa Kronstad, Ph.D.
Postdoctoral Scholar
Blish Laboratory  |  Grant Building S164
Department of Medicine  |  Division of Infectious Diseases
Stanford University

On Jul 25, 2016, at 5:00 PM, Robert Bruggner <notifications@github.com<mailto:notifications@github.com>> wrote:


This sounds like the parameter metadata in the FCS file is malformed and hence, Citrus cannot read it using the flowCore package. I would suggest trying to see if you can read the FCS file using flowCore directly. Something like:

library("flowCore")
file = read.fcs("/PATH/TO/FILE.FCS")
pData(parameters(file))

If that fails, then you will need to fix the FCS file before flowCore (and Citrus) will be able to read it.

**Comment by LisaMarieKronstad** [comment] 2016-07-26 17:10
I ended up renaming my files from .fcs --> .FCS. 

Then ran this code: 

library("flowCore")
file = read.FCS("/Users/BlishLab/Desktop/Folder")
pData(parameters(file))

Now it is working - thanks :)

**Comment by bostendorf** [comment] 2016-09-19 13:17
Unfortunately I ran into the same problem. FCS-files exported either directly from FACSDiva or re-exported from Flojo (either 8.7 or 10.0.7) cannot be read into Citrus and give this error message:

Error in value[[3L]](cond) : 
  Unexpected Error: Error in pnames[sapply(pnames, nchar) < 3] = parameterNames[sapply(pnames, : NAs are not allowed in subscripted assignments

The files from FACSDiva can be read by the flowcore package and the pData command also works on them. Any help is greatly appreciated!

**Comment by SamGG** [comment] 2016-09-19 13:50
Hi,
The code is at https://github.com/nolanlab/citrus/blob/0d308ab77719aaba0eed3a4983300ec72396cf31/R/citrus.launchUI.R#L56-L58
Once you read your FCS file using flowCore, investigate 
```r
(parameterNames = colnames(fcsFile))
(pnames = as.vector(pData(flowCore::parameters(fcsFile))$desc))
sapply(pnames,nchar)<3  # is there any NA here?
```

**Comment by bostendorf** [comment] 2016-09-19 14:04
Hi Sam,
thanks a lot for your prompt reply! Yes, in fact there's a couple of NA's there. I guess I need to get rid of all the non-defined parameters there?

**Comment by SamGG** [comment] 2016-09-19 14:12
Well it depends if you want to build the analysis on those parameters. If not confidential, could you post the output of the command?

**Comment by bostendorf** [comment] 2016-09-19 14:15
Sure: 

sapply(pnames,nchar)<3  # is there any NA here?
            <NA>             <NA>             <NA>             <NA>             <NA>       FITC_F4_80             <NA> PerCP-Cy5_5_Ly6G 
              NA               NA               NA               NA               NA            FALSE               NA            FALSE 
       APC             <NA>       MHCII             <NA>      BV605       BV711       BV785 
           FALSE               NA            FALSE            FALSE               NA            FALSE            FALSE            FALSE 
     BUV395             <NA>             <NA>          PE          mCherry             <NA>     PE-Cy7 
           FALSE               NA               NA            FALSE            FALSE               NA            FALSE 
>

**Comment by SamGG** [comment] 2016-09-19 14:44
Without a fixed font, the resulting list is not crystal clear. 
I think that if you insert before line 58 something like, it should work. It is intended to replace NA description by original channel name.
```r
pnames[is.na(pnames,nchar)] = parameterNames[is.na(pnames,nchar)]
```
So, please do run the following code on your FCS flowFrame. There is no error reported, and pnames should sounds great.
```r
  parameterNames = flowCore::colnames(fcsFile)
  pnames = as.vector(pData(flowCore::parameters(fcsFile))$desc)
  pnames[is.na(pnames,nchar)] = parameterNames[is.na(pnames,nchar)]
  pnames[sapply(pnames,nchar)<3] = parameterNames[sapply(pnames,nchar)<3]
  # Check
  pnames
```
Once checked, I think the quickest workaround is to start a new copy of Citrus (just fork it), then insert the new line in the code, and finally install Citrus on your computer using your new repository.
I will be off for one hour...

**Comment by bostendorf** [comment] 2016-09-19 15:43
Great, after inserting 

`pnames[is.na(pnames)] = parameterNames[is.na(names)]`

before line 58 the files are properly read in (I deleted the ",nchar", since is.na complained about passing on two arguments). 
One strange thing is that now all parameters are displayed twice (some even three times) in the GUI. Thanks a lot and I'll post how it goes!

**Comment by SamGG** [comment] 2016-09-19 17:17
Sorry for the extra ",nchar". Bad copy/paste.
Concerning the last error, either fileSampleSize is NA, either nrow(fcsData) is NA. Both are weird. May be the problem arises from the previous change. I think we should try to avoid any replacement in the getFileParamters function. To do so, insert the following line 
```r
  parameterNames = flowCore::colnames(fcsFile)
  return(parameterNames)  # line to insert
  pnames = as.vector(pData(flowCore::parameters(fcsFile))$desc)
```
For the scaling, I think Robert is the right person.
HTH

**Comment by bostendorf** [comment] 2016-09-19 17:29
I'm afraid the same error message persists after adding the line above..

>
> Error in if ((!is.null(fileSampleSize)) && (fileSampleSize < nrow(fcsData))) { : 
  missing value where TRUE/FALSE needed
>

**Comment by SamGG** [comment] 2016-09-19 18:46
At https://github.com/bostendorf/citrus/blob/master/R/citrus.util.R#L82 put 
```r
browser()
```
And start debugging... ie when the Citrus stops because the debugger starts, try to guess if any of fileSampleSize or nrow(fcsData) is NA. If both variables look alright, then try piece of the code that raises an error.
Alternatively, you could attach a sampling of your FCS file to this thread.
The mentioned scaling consists in centering and dividing by standard deviation. If  each column (aka channel) of your fcs files covers the same scale, I don't think you need this scaling. Depending on the amount of positive and negative events, scaling could lead to very different results although the original data cover the same scale.

**Comment by rbruggner** [comment] 2016-09-23 06:32
If there’s a problematic FCS file that you can share with me, I can potentially take a crack at fixing.

**Comment by bostendorf** [comment] 2016-09-23 17:08
Thanks a lot for the offer, Robert. I'm sending you a file as a PM.

**Comment by rbruggner** [comment] 2016-10-05 05:31
I've made a new branch called ndDscrpt (bad name, I know) but it attempts to handle NA's in the FCS file parameter descriptions. You should be able to install it with: 

`install_github("nolanlab/citrus",ref="naDscrpt")`

Please give it a try and let me know if it works. If so, will merge with master branch.

**Comment by bostendorf** [comment] 2016-10-05 18:22
Thanks so much for looking into this, Robert!
Unfortunately, now the clustering aborts with R encountering a fatal error. I attached links to one sample .fcs file as well as the R-script generated by Citrus. 
Please let me know if there is anything else I should provide. 

Thanks again!
Ben


Link to example fcs-file <https://dl.dropboxusercontent.com/u/4270380/tumor_A_1_004.fcs>

**Comment by rbruggner** [comment] 2016-10-05 18:29
Can you attach an error log (the output of the citrus run) as well please?

**Comment by zhanxw** [comment] 2016-10-09 03:54
I installed citrus from source codes from branch `naDscrpt`. 
R crashed when I started to run example 1. 

The console output is:

> Reading Condition  defaultCondition 
> 	Reading file  Patient01_healthy.fcs 
> 	Reading file  Patient02_healthy.fcs 
> 	Reading file  Patient03_healthy.fcs 
> 	Reading file  Patient04_healthy.fcs 
> 	Reading file  Patient05_healthy.fcs 
> 	Reading file  Patient06_healthy.fcs 
> 	Reading file  Patient07_healthy.fcs 
> 	Reading file  Patient08_healthy.fcs 
> 	Reading file  Patient09_healthy.fcs 
> 	Reading file  Patient10_healthy.fcs 
> 	Reading file  Patient11_diseased.fcs 
> 	Reading file  Patient12_diseased.fcs 
> 	Reading file  Patient13_diseased.fcs 
> 	Reading file  Patient14_diseased.fcs 
> 	Reading file  Patient15_diseased.fcs 
> 	Reading file  Patient16_diseased.fcs 
> 	Reading file  Patient17_diseased.fcs 
> 	Reading file  Patient18_diseased.fcs 
> 	Reading file  Patient19_diseased.fcs 
> 	Reading file  Patient20_diseased.fcs 
> Clustering 20000 events
  

R crashed at `citrus.full()` function.

**Comment by zhanxw** [comment] 2016-10-09 04:04
I also tried to install citrus from github master branch.
Citrus also crashed when analyzing example 1.
How to fix the crash problem?

**Comment by rbruggner** [comment] 2016-10-12 15:33
@zhanxw This sounds like a different problem. Can you please open a new issue and provide details of the operating system, R session info, etc etc?

**Comment by rbruggner** [comment] 2016-10-12 15:35
Thread, AFAICT, the primary issue in this thread was the handling of NAs in parameter descriptions and I believe the naDscrpt branch fixes that problem, but would love confirmation.

I'm going to close this for the moment, but if it turns out that it's related or the NA problem isn't fixed, can re-open.

**Closed by rbruggner** 2016-10-12 15:35 UTC

**Comment by bostendorf** [comment] 2016-10-17 13:59
I'm sorry for the late reply - I can confirm that the naDscrpt branch seems to fix the problem, thanks very much for the quick fix!

**Comment by zhanxw** [comment] 2016-10-17 14:00
It also fixed the problem in my analysis. Thanks.

**Comment by rbruggner** [comment] 2016-10-17 17:39
Ok - will merge with master. If you're still having trouble with citrus crashing, please feel free to open a new issue.
