### ISSUE TITLE
frequently stopped "R"

### ISSUE THREAD

**Issue by kdh4win4** [nolanlab/citrus#105] opened 2016-10-25 15:09 UTC
Dear 

Greetings ~~
I would like to know why citrus is not working well. 
Well, I have many fcs files with unstim, stim1, stim2, stim3 conditions.
Most of time, R stopped suddenly. 
The suspicious reason would be large sample size or uneven number of samples (41 vs 40). 
Any comments would be appreciated.

**Comment by rbruggner** [comment] 2016-10-25 15:14
In order to help debug, Please attach the contents of the citrus.log file as well as any error messages that you may see.

**Comment by kdh4win4** [comment] 2016-10-25 15:28
There is not much information in log file. 
So I attached screenshot. 
[citrus_log.docx](https://github.com/nolanlab/citrus/files/551012/citrus_log.docx)
My file size is big ?
I compared two sample (25 vs. 25)
![screen shot 2016-10-25 at 11 25 48 am](https://cloud.githubusercontent.com/assets/12645005/19692437/f01172fe-9aa5-11e6-8348-73efc04631b9.png)
![screen shot 2016-10-25 at 11 27 10 am](https://cloud.githubusercontent.com/assets/12645005/19692489/17b91514-9aa6-11e6-9e33-d745a203b1eb.png)
![screen shot 2016-10-25 at 11 27 24 am](https://cloud.githubusercontent.com/assets/12645005/19692491/17c0a78e-9aa6-11e6-8a00-85b4abff6733.png)
![screen shot 2016-10-25 at 11 27 34 am](https://cloud.githubusercontent.com/assets/12645005/19692492/17c162f0-9aa6-11e6-96a8-2e6898eddad3.png)
![screen shot 2016-10-25 at 11 27 44 am](https://cloud.githubusercontent.com/assets/12645005/19692490/17bcc81c-9aa6-11e6-9b77-9031c6319475.png)

**Comment by rbruggner** [comment] 2016-10-25 15:37
Can you please describe what happens when R stops, or attach a screenshot of any error message that appears? 

And just to confirm, you have 10 cores in the computer that you're running on?

**Comment by kdh4win4** [comment] 2016-10-25 15:44
My mac has 8 cores. 
However, sometimes 10 cores worked on CITRUS UI v0.8 with small (100 or 200) events number.
I am running 4 cores now. if I have error sign I would attached it.

**Comment by kdh4win4** [comment] 2016-10-25 15:45
![screen shot 2016-10-25 at 11 45 05 am](https://cloud.githubusercontent.com/assets/12645005/19693146/847f829e-9aa8-11e6-9b7b-687d50fb85cc.png)

**Comment by kdh4win4** [comment] 2016-10-25 15:47
Above error sign is caused by 1000 events/5% 
![screen shot 2016-10-25 at 11 46 20 am](https://cloud.githubusercontent.com/assets/12645005/19693228/c4a63084-9aa8-11e6-924f-6b379adbbf2b.png)
![screen shot 2016-10-25 at 11 46 30 am](https://cloud.githubusercontent.com/assets/12645005/19693230/c4af36d4-9aa8-11e6-9382-0d784fed3d88.png)
![screen shot 2016-10-25 at 11 46 38 am](https://cloud.githubusercontent.com/assets/12645005/19693227/c4a359ae-9aa8-11e6-868e-0b47b74f748d.png)
![screen shot 2016-10-25 at 11 46 47 am](https://cloud.githubusercontent.com/assets/12645005/19693229/c4abbe14-9aa8-11e6-89dc-e00548fdedf6.png)
![screen shot 2016-10-25 at 11 46 54 am](https://cloud.githubusercontent.com/assets/12645005/19693231/c4bb9db6-9aa8-11e6-8b9a-a826764c1564.png)

**Comment by kdh4win4** [comment] 2016-10-25 18:16
I have 3GHz 8-core computer.
However, sometimes with small events (100 or 200 per file) 10 core works.
Anyway I will use less than 8 core.
RStudio is suddenly quitted with error sign.


Sincerely,
Dohoon Kim

**Comment by kdh4win4** [comment] 2016-10-26 15:40
Is it too big ? did you get my email ?

**Comment by kdh4win4** [comment] 2016-10-26 19:48
When I set two groups. 
It suddenly stopped !
![screen shot 2016-10-26 at 3 47 12 pm](https://cloud.githubusercontent.com/assets/12645005/19742571/9f4c27d0-9b93-11e6-9f12-2b6bcc4910f1.png)

Error sign says, 
**Listening on http://127.0.0.1:5703
simpleWarning: Error in =: 'names' attribute [19] must be the same length as the vector [18]**

**Comment by kdh4win4** [comment] 2016-10-26 19:51
Dear CITRUS team, 
Any comments would be appreciated. 
Thank you

**Comment by rbruggner** [comment] 2016-10-31 03:43
The crashes sounds like a potential problem with the clustering algorithm. This could potentially be caused by a memory leak, or supporting packages being compiled with different compilers. 

Did you install using the 1) "Standard Citrus Installation" directions or 2) Citrus installation Using Mac Ports and g++4.8?

**Comment by kdh4win4** [comment] 2016-10-31 17:28
I think I used #1 method like below;

library("devtools")

source("https://bioconductor.org/biocLite.R")
biocLite("impute")
biocLite("brew")

install_github('nolanlab/citrus')

library("citrus")
citrus.launchUI()

**Comment by kdh4win4** [comment] 2016-12-13 15:39
Can I get any more comment ?
Actually, Citrus does not look active program anymore.

**Comment by SamGG** [comment] 2016-12-13 16:37
I think Citrus is still active, but you are right to ask again for help. I can't help you on a question that seems specific to Mac. I think somebody will answer you. Best.

**Comment by kdh4win4** [comment] 2016-12-13 18:34
I find out something. if my clustering events number is more than 3000 ~ 4000, the R program suddenly stopped. So I minimize my sample numbers 3~4, minimize clustering parameter into 3~5, then CITRUS is working. However, I need more parameters and more samples. Is it impossible or somebody can help this please ?

**Comment by SamGG** [comment] 2016-12-13 21:13
Just a two cents proposal: 1000 events per file (for a total of 50 files) is OK as long as the total number of events is below 50K or 60K events (see Rclusterpp limits). 1% or 2% as cluster size sounds OK (5% might be too big to get a relevant feature). I think the channels selected for the clustering parameters should not include the channels selected for the median parameters, if medians is selected as feature types. Finally, check cross validation value unless 1 means no cross validation. Alternatively, you should test with 10 samples per group and 1k events. 10 is usually enough for non parametric statistics.
HTH

**Comment by kdh4win4** [comment] 2016-12-13 21:35
I appreciate this tip. I will try soon. 

Sincerely,
Dohoon Kim

2016. 12. 13. 오후 4:13 SamGG <notifications@github.com> 작성:

**Comment by rbruggner** [comment] 2016-12-19 01:49
One thought I had is that you may be experiencing a memory leak in Rclusterpp that may be fixed in Version 0.2.4 (which is not on cran). 
You can install as follows: 
```
install.packages(c("Rcpp","RcppEigen"),type="source")
library("devtools")
install_github('nolanlab/Rclusterpp')
install_github('nolanlab/citrus')
```
Let me know if that fixes the problems?

**Comment by rbruggner** [comment] 2017-03-01 05:45
Any update as to if this fixed the problem? I think it's probably the same issue experienced in #110 . Seems to be related to the release of Mac OS X 10.12 which I did not have access to until recently.

**Comment by kdh4win4** [comment] 2017-03-01 15:10
I haven't spent much time on this issue recently. I will let you know if I
found any progress. Thank you.

Sincerely,
Dohoon Kim

**Closed** 2017-03-01 15:35 UTC
